sudo: required
services:
    - docker

before_install:
    - docker build -t stevejohansson/docker-react -f Dockerfile.dev .

    script:
    - docker run -e CI=true stevejohansson/docker-react npm run test    

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-central-1"    
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-873116259517"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY  
