sudo: required
services:
    - docker

before_install:
    - docker build -t stevejohansson/docker-react -f Dockerfile.dev .

    script:
    - docker run -e CI=true stevejohansson/docker-react npm run test    